[theme]
base = "dark"
primaryColor = "#ffffff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#141414"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
